-- DRAFT: verify against current Snowflake CREATE SEMANTIC VIEW syntax before running.
CREATE OR REPLACE SEMANTIC VIEW FINTECH_TRANSACTION_INTELLIGENCE
  TABLES (
    transaction_top AS LANDING.FINTECH.TRANSACTION_TOP,
    agg_user AS LANDING.FINTECH.AGG_USER,
    agg_transaction AS LANDING.FINTECH.AGG_TRANSACTION,
    map_transaction AS LANDING.FINTECH.MAP_TRANSACTION,
    top_user AS LANDING.FINTECH.TOP_USER,
    map_user AS LANDING.FINTECH.MAP_USER
  )
  FACTS (
    transaction_top.AMOUNT AS TRANSACTION_TOP_AMOUNT,
    transaction_top.COUNT AS TRANSACTION_TOP_COUNT,
    agg_user.PERCENTAGE AS AGG_USER_PERCENTAGE,
    agg_user.COUNT AS AGG_USER_COUNT,
    agg_transaction.AMOUNT AS AGG_TRANSACTION_AMOUNT,
    agg_transaction.COUNT AS AGG_TRANSACTION_COUNT,
    map_transaction.AMOUNT AS MAP_TRANSACTION_AMOUNT,
    map_transaction.COUNT AS MAP_TRANSACTION_COUNT,
    top_user.REGISTERED_USERS AS TOP_USER_REGISTERED_USERS,
    map_user.REGISTERED_USERS AS MAP_USER_REGISTERED_USERS,
    map_user.APP_OPENS AS MAP_USER_APP_OPENS
  )
  DIMENSIONS (
    transaction_top.ENTITY_NAME AS TRANSACTION_TOP_ENTITY_NAME,
    transaction_top.QUARTER AS TRANSACTION_TOP_QUARTER,
    transaction_top.STATE AS TRANSACTION_TOP_STATE,
    transaction_top.YEAR AS TRANSACTION_TOP_YEAR,
    transaction_top._FIVETRAN_DELETED AS TRANSACTION_TOP__FIVETRAN_DELETED,
    transaction_top._FIVETRAN_SYNCED AS TRANSACTION_TOP__FIVETRAN_SYNCED,
    agg_user.BRAND AS AGG_USER_BRAND,
    agg_user.QUARTER AS AGG_USER_QUARTER,
    agg_user.STATE AS AGG_USER_STATE,
    agg_user.YEAR AS AGG_USER_YEAR,
    agg_user._FIVETRAN_DELETED AS AGG_USER__FIVETRAN_DELETED,
    agg_user._FIVETRAN_SYNCED AS AGG_USER__FIVETRAN_SYNCED,
    agg_transaction.NAME AS AGG_TRANSACTION_NAME,
    agg_transaction.QUARTER AS AGG_TRANSACTION_QUARTER,
    agg_transaction.STATE AS AGG_TRANSACTION_STATE,
    agg_transaction.YEAR AS AGG_TRANSACTION_YEAR,
    agg_transaction._FIVETRAN_DELETED AS AGG_TRANSACTION__FIVETRAN_DELETED,
    agg_transaction._FIVETRAN_SYNCED AS AGG_TRANSACTION__FIVETRAN_SYNCED,
    map_transaction.NAME AS MAP_TRANSACTION_NAME,
    map_transaction.QUARTER AS MAP_TRANSACTION_QUARTER,
    map_transaction.STATE AS MAP_TRANSACTION_STATE,
    map_transaction.YEAR AS MAP_TRANSACTION_YEAR,
    map_transaction._FIVETRAN_DELETED AS MAP_TRANSACTION__FIVETRAN_DELETED,
    map_transaction._FIVETRAN_SYNCED AS MAP_TRANSACTION__FIVETRAN_SYNCED,
    top_user.NAME AS TOP_USER_NAME,
    top_user.QUARTER AS TOP_USER_QUARTER,
    top_user.STATE AS TOP_USER_STATE,
    top_user.YEAR AS TOP_USER_YEAR,
    top_user._FIVETRAN_DELETED AS TOP_USER__FIVETRAN_DELETED,
    top_user._FIVETRAN_SYNCED AS TOP_USER__FIVETRAN_SYNCED,
    map_user.DISTRICT AS MAP_USER_DISTRICT,
    map_user.QUARTER AS MAP_USER_QUARTER,
    map_user.STATE AS MAP_USER_STATE,
    map_user.YEAR AS MAP_USER_YEAR,
    map_user._FIVETRAN_DELETED AS MAP_USER__FIVETRAN_DELETED,
    map_user._FIVETRAN_SYNCED AS MAP_USER__FIVETRAN_SYNCED
  )
  METRICS (
    transaction_top.total_amount AS SUM(AMOUNT),
    transaction_top.total_count AS SUM(COUNT),
    agg_user.total_percentage AS SUM(PERCENTAGE),
    agg_user.total_count AS SUM(COUNT),
    agg_transaction.total_amount AS SUM(AMOUNT),
    agg_transaction.total_count AS SUM(COUNT),
    map_transaction.total_amount AS SUM(AMOUNT),
    map_transaction.total_count AS SUM(COUNT),
    top_user.total_registered_users AS SUM(REGISTERED_USERS),
    map_user.total_registered_users AS SUM(REGISTERED_USERS),
    map_user.total_app_opens AS SUM(APP_OPENS)
  );
